### ISSUE TITLE
The enemies health is 0 in some room if you do not press cheat

### ISSUE THREAD

**Issue by Toixel** [EthanVB123/TomTangEthanVanBruchemSem2Project#6]

**Comment by EthanVB123** [comment]
I noticed that the enemy health doesn't change when you enter a new room.
If you knocked an enemy down to 1 hp, then the enemy in the same list position in all other rooms is 1 hp.

However, I haven't yet fixed the list.

**Comment by EthanVB123** [comment]
FIXED! I fixed this bug in the 'Enemy health fixed' commit.
This bug occurred because in the reviveEnemy(x) function, there wasn't anything that altered the enemy's health: it just fixed their actions and damage.
